name = "PrometheusNode"
identifier = "net.prometheus.node"
icon = ["Prometheus.png"]
version = "1.0.0"
copyright = "Copyright (c) Prometheus Network Solutions 2019. All rights reserved."
short_description = "Prometheus Network Solutions"
long_description = """
PrometheusNode allows users to acquire cryptocurrency while contributing in a decentralized network.
"""
